- hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: webserver
      #      image: "kimjuhyo/hello:{{ lookup('env','BUILD_NUMBER') }}"
      image: "kimjuhyo/hello:2"
      state: started
      ports:
      - "80:8080"


